language: R
sudo: false
dist: xenial
cache:
  packages: true
  directories:
  - $HOME/usr/local

addons:
  apt:
    packages:
    - libglu1-mesa-dev

before_install:
  - curl -OL https://raw.githubusercontent.com/jefferis/nat/master/build-cmtk.sh
  - bash build-cmtk.sh
  - export PATH=$PATH:$HOME/usr/local/bin

services:
  - xvfb
