language: R
sudo: false
dist: trusty
cache:
  packages: true
  directories:
  - $HOME/usr/local

before_script:
  - export PATH=$PATH:$HOME/usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
